services:
  - type: web
    name: welder-fabrication-workshop
    env: docker
    buildCommand: mvn clean package -DskipTests
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080 